const steps = [["Discover", "Read configured RSS feeds and source pages."], ["Read", "Extract available article text and source metadata."], ["Qualify", "Require a date, state and town or LGA where available."], ["Reconcile", "Compare incident fingerprints to reduce duplication."], ["Publish", "Show reporting status and source evidence with each record."]];
const evidence = [["Confirmed", "Two or more cited sources, or an official statement plus a cited publisher."], ["Developing", "Credible reporting exists, but important details or outcomes may still change."], ["Unconfirmed", "A single source or incomplete corroboration; use with additional caution."]];
const fields = [["Incident", "Title, factual summary and incident date"], ["Location", "State, LGA, town and coordinates when available"], ["Attribution", "Reported group or unknown; never inferred for certainty"], ["Human impact", "Killed, injured, abducted and displaced; unknown remains unknown"], ["Evidence", "Publisher, source title, URL and review state"], ["Record history", "Created and updated timestamps when returned by the database"]];
const limits = [["Coverage is incomplete", "Source availability, redirects, rate limits and missing local reporting create gaps."], ["Dates and places can conflict", "Publication date is never treated as the incident date without supporting information."], ["Numbers are reported minimums", "Figures may change. Missing counts remain unknown rather than becoming zero."], ["Automation has limits", "Source discovery can miss events or confuse related stories. Publication is not a reliability percentage."]];

export default function AboutPage() {
  return <div className="page-wrap">
    <header className="page-header"><div><span className="eyebrow">Methodology & limitations</span><h1>A record, not a prediction.</h1><p className="lede">NATracker organizes published reporting about security incidents in Nigeria. It is designed for research and awareness, not real-time safety decisions.</p></div><aside className="panel panel--danger"><span className="eyebrow">Important</span><p className="supporting">Publication does not prove completeness or accuracy. Open the cited sources before using a record.</p></aside></header>
    <section><h2>How a report becomes a record</h2><div className="method-steps">{steps.map(([title, description], index) => <article className="card method-step" key={title}><span className="step-number">{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section>
    <section><div className="section-heading"><h2>Evidence labels</h2></div><div className="method-cards">{evidence.map(([title, description]) => <article className="card method-card" key={title}><span className={`status ${title === "Confirmed" ? "status--confirmed" : title === "Developing" ? "status--developing" : ""}`}>{title}</span><p>{description}</p></article>)}</div></section>
    <section><div className="section-heading"><h2>What each record contains</h2></div><div className="field-list">{fields.map(([label, description]) => <article className="card field-row" key={label}><strong>{label}</strong><span>{description}</span></article>)}</div></section>
    <section><div className="section-heading"><h2>Known limitations</h2></div><div className="limit-list">{limits.map(([title, description], index) => <article className={`card limit-card ${index === limits.length - 1 ? "limit-card--critical" : ""}`} key={title}><h3>{title}</h3><p>{description}</p></article>)}</div></section>
    <section className="panel panel--notice" style={{ marginTop: "2rem" }}><span className="eyebrow">Corrections</span><p className="supporting"><strong>Every record retains its supplied sources and timestamps.</strong> When a source is corrected or a report changes, figures should be reviewed against the cited source before the record is updated.</p></section>
  </div>;
}
