"use client";

import Link from "next/link";
import { MagnifyingGlassIcon } from "@heroicons/react/24/outline";
import { useCallback, useEffect, useState } from "react";
import { ErrorState, LoadingState } from "@/components/DataState";
import LoginModal from "@/components/LoginModal";
import SearchableSelect from "@/components/SearchableSelect";
import { STATE_FILTER_OPTIONS, STATUS_FILTER_OPTIONS } from "@/lib/filter-options";
import { IncidentRecord, formatDate, statusLabel } from "@/lib/incident-view";

type Pagination = { page: number; total: number; totalPages: number; hasNext: boolean; hasPrev: boolean };

export default function AdminPage() {
  const [auth, setAuth] = useState<boolean | null>(null); const [records, setRecords] = useState<IncidentRecord[]>([]); const [pagination, setPagination] = useState<Pagination | null>(null); const [loading, setLoading] = useState(false); const [failed, setFailed] = useState(false); const [search, setSearch] = useState(""); const [searchInput, setSearchInput] = useState(""); const [state, setState] = useState(""); const [status, setStatus] = useState(""); const [page, setPage] = useState(1); const [selected, setSelected] = useState<string[]>([]); const [reason, setReason] = useState(""); const [confirmation, setConfirmation] = useState(""); const [actionError, setActionError] = useState(""); const [moving, setMoving] = useState(false);
  const checkAuth = useCallback(async () => { try { const response = await fetch("/api/auth/check", { cache: "no-store" }); setAuth(response.ok); } catch { setAuth(false); } }, []);
  useEffect(() => { checkAuth(); }, [checkAuth]);
  const load = useCallback(async () => { if (!auth) return; setLoading(true); setFailed(false); try { const query = new URLSearchParams({ page: String(page), limit: "12", sort: "date_desc" }); if (search) query.set("search", search); if (state) query.set("state", state); if (status) query.set("status", status); const response = await fetch(`/api/attacks?${query}`, { cache: "no-store" }); if (!response.ok) throw new Error("Unable to load records"); const payload = await response.json(); setRecords(payload.attacks ?? []); setPagination(payload.pagination ?? null); } catch { setFailed(true); } finally { setLoading(false); } }, [auth, page, search, state, status]);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { const timer = window.setTimeout(() => { setSearch(searchInput); setPage(1); }, 350); return () => window.clearTimeout(timer); }, [searchInput]);
  const toggle = (id: string, checked: boolean) => setSelected((current) => checked ? [...current, id] : current.filter((item) => item !== id));
  const moveToReview = async () => { setActionError(""); const expected = `MOVE ${selected.length} RECORDS TO REVIEW`; if (!selected.length || confirmation !== expected || reason.trim().length < 8) { setActionError(`Enter a reason and type “${expected}” to continue.`); return; } setMoving(true); try { const response = await fetch("/api/admin/incidents/delete", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ids: selected, reason, confirmation }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Unable to move records to review"); setSelected([]); setReason(""); setConfirmation(""); await load(); } catch (error) { setActionError(error instanceof Error ? error.message : "Unable to move records to review"); } finally { setMoving(false); } };
  if (auth === null) return <div className="page-wrap"><LoadingState label="Checking administration access" /></div>;
  if (!auth) return <LoginModal onSuccess={() => setAuth(true)} />;
  const singleSource = records.filter((item) => (item.sources?.length || 0) < 2).length; const unconfirmed = records.filter((item) => item.status === "unconfirmed").length; const unknownImpact = records.filter((item) => Object.values(item.casualties).some((value) => value == null)).length; const expected = `MOVE ${selected.length} RECORDS TO REVIEW`;
  return <div className="page-wrap--wide">
    <header className="admin-top"><div><span className="eyebrow">Administration</span><h1>Record management</h1><p className="lede">Review records, source receipts and data-quality exceptions.</p></div><aside className="panel panel--caution"><span className="eyebrow">Protected workspace</span><p className="supporting">Public removal is a soft deletion with a typed reason and timestamp. It does not permanently delete the record.</p></aside></header>
    <section className="metric-grid"><Metric label="Active records" value={pagination?.total ?? 0} /><Metric label="Sources on page" value={records.reduce((count, item) => count + (item.sources?.length || 0), 0)} className="metric-card--evidence" /><Metric label="Single-source on page" value={singleSource} className="metric-card--caution" /><Metric label="Unconfirmed on page" value={unconfirmed} className="metric-card--muted" /></section>
    <section className="panel filter-panel"><div className="search-row search-row--admin"><div className="search-wrap"><MagnifyingGlassIcon aria-hidden="true" /><label className="sr-only" htmlFor="admin-search">Search records</label><input id="admin-search" className="control" value={searchInput} onChange={(event) => setSearchInput(event.target.value)} placeholder="Search title, source URL or record location" /></div><label className="filter-label filter-label--compact" htmlFor="admin-state-filter">State<SearchableSelect inputId="admin-state-filter" ariaLabel="Filter administration records by state" options={STATE_FILTER_OPTIONS} value={state} onChange={(value) => { setState(value); setPage(1); }} /></label><label className="filter-label filter-label--compact" htmlFor="admin-status-filter">Status<SearchableSelect inputId="admin-status-filter" ariaLabel="Filter administration records by evidence status" options={STATUS_FILTER_OPTIONS} value={status} onChange={(value) => { setStatus(value); setPage(1); }} /></label></div></section>
    <section className="admin-layout"><div><div className="panel"><div className="panel-heading"><div><h2>Records</h2><p className="panel-subtitle">Select records only after reviewing their sources.</p></div><span className="evidence-count">{pagination?.total ?? 0} total</span></div>{loading ? <LoadingState label="Loading administration records" /> : null}{failed ? <ErrorState retry={load} /> : null}{!loading && !failed ? <div>{records.map((record) => <article className="admin-record" key={record._id}><input id={`record-${record._id}`} type="checkbox" checked={selected.includes(record._id)} onChange={(event) => toggle(record._id, event.target.checked)} /><div><label className="sr-only" htmlFor={`record-${record._id}`}>Select {record.title}</label><span className="record-card__date">{formatDate(record.date)} · {record.location.state}</span><Link href={`/incidents/${record._id}`} className="admin-record__title">{record.title}</Link><span className="admin-record__place">{record.location.town !== "Unknown" ? record.location.town : record.location.lga}</span></div><span className={`status ${record.status === "confirmed" ? "status--confirmed" : record.status === "developing" ? "status--developing" : ""}`}>{statusLabel(record.status)}</span><span className="evidence-count">{record.sources?.length || 0} linked<br /><Link className="text-link" href={`/incidents/${record._id}`}>Open →</Link></span></article>)}</div> : null}</div>{pagination && pagination.totalPages > 1 ? <nav className="panel pagination" aria-label="Administration pagination"><button type="button" className="button-quiet" disabled={!pagination.hasPrev || loading} onClick={() => setPage((value) => Math.max(1, value - 1))}>Previous</button><span className="pagination__label">Page {pagination.page} of {pagination.totalPages}</span><button type="button" className="button-quiet" disabled={!pagination.hasNext || loading} onClick={() => setPage((value) => value + 1)}>Next →</button></nav> : null}</div>
      <aside className="admin-side"><section className="panel"><h2>Data-quality queue</h2><p className="panel-subtitle">Current page; these are review prompts, not automatic deletion.</p><Queue value={singleSource} label="Single-source records" /><Queue value={unconfirmed} label="Unconfirmed records" /><Queue value={unknownImpact} label="Unknown impact fields" /><Queue value={records.filter((item) => !item.location.lga || item.location.lga === "Unknown").length} label="Location precision checks" /></section><section className="panel"><h2>Safer bulk actions</h2><p className="supporting">Removing records from the public list keeps them in the database with the reason, actor and timestamp. Permanent retention changes require a separately audited workflow.</p><div className="confirmation" style={{ marginTop: "1rem" }}><label>Review reason<textarea value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Explain why these records need review" /></label><label>Type to confirm<input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} placeholder={expected} /></label>{actionError ? <p style={{ margin: 0, color: "var(--burgundy)", fontWeight: 700 }}>{actionError}</p> : null}<button className="button" type="button" disabled={!selected.length || moving} onClick={moveToReview}>{moving ? "Moving records…" : `Move ${selected.length || "selected"} to review`}</button></div></section><section className="panel panel--notice"><span className="eyebrow">Collector status</span><p className="supporting">Collection health is not verified in this browser session.</p></section></aside>
    </section>
  </div>;
}
function Metric({ label, value, className = "" }: { label: string; value: number; className?: string }) { return <article className={`metric-card ${className}`}><div className="metric-card__label">{label}</div><div className="metric-card__value">{value.toLocaleString("en-NG")}</div><span className="metric-card__detail">visible dataset</span></article>; }
function Queue({ value, label }: { value: number; label: string }) { return <div className="queue-item"><strong>{value}</strong><span>{label}</span></div>; }
