"use client";

import { FormEvent, useState } from "react";

export default function LoginModal({ onSuccess }: { onSuccess: () => void }) {
  const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(""); try { const response = await fetch("/api/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username, password }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Sign-in failed"); onSuccess(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Sign-in failed"); } finally { setLoading(false); } };
  return <div style={{ display: "grid", placeItems: "center", minHeight: "60vh" }}><section className="panel" style={{ width: "min(100%, 28rem)" }}><span className="eyebrow">Protected workspace</span><h1 style={{ fontSize: "2rem" }}>Administration sign-in</h1><p className="supporting">Access to record management is restricted to authorised administrators.</p><form className="confirmation" style={{ marginTop: "1.5rem" }} onSubmit={submit}>{error ? <p className="panel panel--danger" role="alert" style={{ margin: 0, padding: ".75rem" }}>{error}</p> : null}<label>Username<input autoComplete="username" value={username} onChange={(event) => setUsername(event.target.value)} required /></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} required /></label><button className="button" disabled={loading}>{loading ? "Signing in…" : "Sign in"}</button></form></section></div>;
}
