"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { EmptyState, ErrorState, LoadingState } from "@/components/DataState";
import RecordCard from "@/components/RecordCard";
import { IncidentRecord, displayValue, formatDateLong, locationLabel, statusLabel } from "@/lib/incident-view";

export default function IncidentDetailPage() {
  const params = useParams<{ id: string }>(); const id = params.id;
  const [record, setRecord] = useState<IncidentRecord | null>(null); const [related, setRelated] = useState<IncidentRecord[]>([]); const [loading, setLoading] = useState(true); const [failed, setFailed] = useState(false); const [notFound, setNotFound] = useState(false); const [offline, setOffline] = useState(false);
  const load = useCallback(async () => { if (!id) return; setLoading(true); setFailed(false); setNotFound(false); setOffline(typeof navigator !== "undefined" && !navigator.onLine); try { const response = await fetch(`/api/attacks/${id}`, { cache: "no-store" }); if (response.status === 404) { setNotFound(true); return; } if (!response.ok) throw new Error("Record unavailable"); const payload = await response.json(); const next = payload.attack as IncidentRecord; setRecord(next); const linked = await fetch(`/api/attacks?state=${encodeURIComponent(next.location.state)}&limit=4&sort=date_desc`, { cache: "no-store" }); if (linked.ok) { const result = await linked.json(); setRelated((result.attacks ?? []).filter((item: IncidentRecord) => item._id !== next._id).slice(0, 3)); } } catch { setFailed(true); } finally { setLoading(false); } }, [id]);
  useEffect(() => { load(); }, [load]);
  if (loading && !record) return <div className="page-wrap"><LoadingState label="Loading incident record" /></div>;
  if (notFound) return <div className="page-wrap"><EmptyState title="Record not found" action={<Link className="button-secondary" href="/incidents">Browse incident records</Link>}>This record may not exist or may no longer be included in the public record.</EmptyState></div>;
  if (failed && !record) return <div className="page-wrap"><ErrorState offline={offline} retry={load} /></div>;
  if (!record) return null;
  const statusClass = record.status === "confirmed" ? "status--confirmed" : record.status === "developing" ? "status--developing" : "";
  return <div className="page-wrap">
    <header className="detail-top detail-top--single"><div><span className="eyebrow">Incidents / {record.location.state || "location unknown"}</span><div style={{ display: "flex", gap: ".5rem", marginTop: "1rem" }}><span className={`status ${statusClass}`}>{statusLabel(record.status)}</span><span className="chip chip--evidence">{record.sources?.length || 0} {record.sources?.length === 1 ? "source" : "sources"}</span></div><h1>{record.title}</h1><p className="detail-meta">{locationLabel(record.location)} </p><p className="detail-fine">Incident date {formatDateLong(record.date)} · Last reviewed {formatDateLong(record.updatedAt)}</p></div></header>
    {failed ? <div className="panel panel--notice" style={{ marginBottom: "1rem", padding: "1rem" }}>Related records could not be refreshed. The record below is from the last successful request. <button type="button" className="text-link" onClick={load}>Retry</button></div> : null}
    <section className="metric-grid" aria-label="Reported human impact"><Metric label="People killed" value={record.casualties.killed} zeroLabel="No deaths reported" className="metric-card--impact" /><Metric label="People injured" value={record.casualties.injured} zeroLabel="No injuries reported" className="metric-card--caution" /><Metric label="People abducted" value={record.casualties.kidnapped} zeroLabel="No abductions reported" className="metric-card--evidence" /><Metric label="People displaced" value={record.casualties.displaced} zeroLabel="No displacement reported" className="metric-card--muted" /></section>
    <section className="detail-layout"><article className="panel"><h2>What was reported</h2><p className="prose">{record.description || "No narrative summary is available for this record."}</p><div className="fact-grid"><div className="fact"><small>Recorded location</small>{locationLabel(record.location)}</div><div className="fact"><small>Reported actor</small>{record.group || "Unknown"}</div><div className="fact"><small>Tags</small>{record.tags?.length ? record.tags.join(", ") : "Not recorded"}</div></div></article><aside className="panel"><div className="panel-heading"><div><h2>Evidence and sources</h2><p className="panel-subtitle">{record.sources?.length || 0} cited reports</p></div></div><div className="source-list">{record.sources?.length ? record.sources.map((source, index) => <article className="source-item" key={`${source.url}-${index}`}><span className="source-item__publisher">{String(index + 1).padStart(2, "0")} · {source.publisher || "Publisher not recorded"}</span><span className="source-item__title">{source.title || "Source title not recorded"}</span><a className="source-item__link" href={source.url} target="_blank" rel="noopener noreferrer">Open source ↗</a></article>) : <p className="supporting">No source links were returned for this record.</p>}</div></aside></section>
    <section><div className="section-heading"><div><h2>Related records</h2><p className="panel-subtitle">Recent records from {record.location.state}; shown in the same readable structure as the archive.</p></div></div>{related.length ? <div className="related-grid">{related.map((item) => <RecordCard key={item._id} incident={item} />)}</div> : <EmptyState title="No related records are available">No other recent records from this state were returned.</EmptyState>}</section>
    <section className="panel panel--alt record-history" style={{ marginTop: "2rem" }}><div className="record-history__heading"><span className="eyebrow">Record history</span><span className="record-history__note">Publication timeline</span></div><div className="history">{record.updatedAt ? <div className="history__event"><time>{formatDateLong(record.updatedAt)}</time><span><strong>Last updated</strong>Record metadata was updated.</span></div> : null}{record.createdAt ? <div className="history__event"><time>{formatDateLong(record.createdAt)}</time><span><strong>Created</strong>Record added to the public incident archive.</span></div> : null}{!record.updatedAt && !record.createdAt ? <div>History timestamps were not returned for this record.</div> : null}</div></section>
  </div>;
}

function Metric({ label, value, zeroLabel, className }: { label: string; value: number | null; zeroLabel: string; className: string }) { const isZero = value === 0; return <article className={`metric-card ${className}`}><div className="metric-card__label">{label}</div><div className={`metric-card__value ${isZero ? "metric-card__value--zero" : ""}`}>{displayValue(value, zeroLabel)}</div><span className="metric-card__detail">{value == null ? "impact reported; figure unknown" : isZero ? "no figure reported for this impact" : "reported figure"}</span></article>; }
